// Code generated by dict2data. DO NOT EDIT.
package py

var polyphonic = map[rune][]Polyphonic{
	'坷': {		{
			Tone: 1,
			Words: []string{"坷垃"},
		},
	},
	'宿': {		{
			Tone: 1,
			Words: []string{"星宿", "八宿"},
		},
		{
			Tone: 2,
			Words: []string{"半宿", "整宿"},
		},
	},
	'叶': {		{
			Tone: 1,
			Words: []string{"叶韵"},
		},
	},
	'载': {		{
			Tone: 1,
			Words: []string{"登载", "转载", "千载"},
		},
	},
	'佣': {		{
			Tone: 1,
			Words: []string{"佣金", "佣钱"},
		},
	},
	'著': {		{
			Tone: 3,
			Words: []string{"穿著", "附著"},
		},
	},
	'晃': {		{
			Tone: 1,
			Words: []string{"摇晃", "晃动"},
		},
	},
	'烙': {		{
			Tone: 1,
			Words: []string{"炮烙"},
		},
	},
	'偻': {		{
			Tone: 1,
			Words: []string{"伛偻"},
		},
	},
	'血': {		{
			Tone: 1,
			Words: []string{"鸡血", "点血"},
		},
	},
	'翘': {		{
			Tone: 1,
			Words: []string{"翘首", "连翘"},
		},
	},
	'杉': {		{
			Tone: 1,
			Words: []string{"杉篙", "杉木"},
		},
	},
	'剿': {		{
			Tone: 1,
			Words: []string{"剿袭", "剿说"},
		},
	},
	'结': {		{
			Tone: 1,
			Words: []string{"结果", "结实"},
		},
	},
	'仅': {		{
			Tone: 3,
			Words: []string{"仅万"},
		},
	},
	'强': {		{
			Tone: 1,
			Words: []string{"勉强", "强迫", "强词"},
		},
		{
			Tone: 2,
			Words: []string{"倔强"},
		},
	},
	'择': {		{
			Tone: 1,
			Words: []string{"择菜", "择席", "择不"},
		},
	},
	'作': {		{
			Tone: 1,
			Words: []string{"作坊", "器作"},
		},
	},
	'芥': {		{
			Tone: 1,
			Words: []string{"芥蓝"},
		},
	},
	'转': {		{
			Tone: 2,
			Words: []string{"转动", "转速"},
		},
	},
	'拗': {		{
			Tone: 1,
			Words: []string{"拗口"},
		},
		{
			Tone: 2,
			Words: []string{"执拗"},
		},
	},
	'估': {		{
			Tone: 1,
			Words: []string{"估衣"},
		},
	},
	'桧': {		{
			Tone: 1,
			Words: []string{"秦桧"},
		},
	},
	'角': {		{
			Tone: 1,
			Words: []string{"角色", "角斗"},
		},
	},
	'涨': {		{
			Tone: 1,
			Words: []string{"泡涨", "脑涨"},
		},
	},
	'绰': {		{
			Tone: 1,
			Words: []string{"宽绰"},
		},
	},
	'几': {		{
			Tone: 1,
			Words: []string{"茶几", "几案"},
		},
	},
	'炮': {		{
			Tone: 1,
			Words: []string{"炮制", "炮格", "炮烙"},
		},
	},
	'仆': {		{
			Tone: 1,
			Words: []string{"仆从", "仆人"},
		},
	},
	'露': {		{
			Tone: 1,
			Words: []string{"露头:露马"},
		},
	},
	'蔓': {		{
			Tone: 1,
			Words: []string{"瓜蔓", "压蔓"},
		},
	},
	'缩': {		{
			Tone: 1,
			Words: []string{"缩砂"},
		},
	},
	'冲': {		{
			Tone: 1,
			Words: []string{"冲床", "冲子"},
		},
	},
	'藉': {		{
			Tone: 1,
			Words: []string{"枕藉", "慰藉"},
		},
	},
	'壳': {		{
			Tone: 1,
			Words: []string{"地壳", "甲壳", "躯壳"},
		},
	},
	'模': {		{
			Tone: 1,
			Words: []string{"模具", "模样"},
		},
	},
	'落': {		{
			Tone: 2,
			Words: []string{"落枕", "落色"},
		},
		{
			Tone: 1,
			Words: []string{"落四", "落下"},
		},
	},
	'殷': {		{
			Tone: 2,
			Words: []string{"殷红"},
		},
		{
			Tone: 1,
			Words: []string{"殷殷"},
		},
	},
	'秘': {		{
			Tone: 1,
			Words: []string{"秘鲁", "秘姓"},
		},
	},
	'疟': {		{
			Tone: 1,
			Words: []string{"疟子"},
		},
	},
	'行': {		{
			Tone: 1,
			Words: []string{"行市", "行伍"},
		},
		{
			Tone: 3,
			Words: []string{"行子"},
		},
		{
			Tone: 4,
			Words: []string{"道行"},
		},
	},
	'荨': {		{
			Tone: 1,
			Words: []string{"荨麻"},
		},
	},
	'暴': {		{
			Tone: 1,
			Words: []string{"地暴"},
		},
	},
	'处': {		{
			Tone: 1,
			Words: []string{"处罚", "处置"},
		},
	},
	'擂': {		{
			Tone: 1,
			Words: []string{"擂台", "打擂"},
		},
	},
	'伯': {		{
			Tone: 3,
			Words: []string{"大伯"},
		},
	},
	'场': {		{
			Tone: 1,
			Words: []string{"场院", "一场"},
		},
		{
			Tone: 1,
			Words: []string{"排场"},
		},
	},
	'脚': {		{
			Tone: 1,
			Words: []string{"脚儿", "脚色"},
		},
	},
	'说': {		{
			Tone: 1,
			Words: []string{"游说", "说客"},
		},
	},
	'都': {		{
			Tone: 1,
			Words: []string{"都市", "大都"},
		},
	},
	'泌': {		{
			Tone: 1,
			Words: []string{"泌阳"},
		},
	},
	'圩': {		{
			Tone: 2,
			Words: []string{"圩场"},
		},
	},
	'中': {		{
			Tone: 1,
			Words: []string{"中奖", "中靶"},
		},
	},
	'刨': {		{
			Tone: 1,
			Words: []string{"刨床", "刨冰"},
		},
	},
	'切': {		{
			Tone: 1,
			Words: []string{"切磋", "切割"},
		},
	},
	'削': {		{
			Tone: 2,
			Words: []string{"切削", "削皮"},
		},
	},
	'粘': {		{
			Tone: 1,
			Words: []string{"粘稠", "粘土"},
		},
	},
	'畜': {		{
			Tone: 1,
			Words: []string{"畜养", "畜牧"},
		},
	},
	'骨': {		{
			Tone: 2,
			Words: []string{"骨碌", "骨朵"},
		},
	},
	'划': {		{
			Tone: 3,
			Words: []string{"划船", "划算"},
		},
	},
	'矜': {		{
			Tone: 1,
			Words: []string{"矜锄"},
		},
	},
	'柞': {		{
			Tone: 1,
			Words: []string{"柞蚕", "柞绸"},
		},
	},
	'吓': {		{
			Tone: 2,
			Words: []string{"威吓", "恐吓"},
		},
	},
	'系': {		{
			Tone: 1,
			Words: []string{"系紧", "系牢"},
		},
	},
	'侥': {		{
			Tone: 1,
			Words: []string{"僬侥"},
		},
	},
	'可': {		{
			Tone: 2,
			Words: []string{"可汗"},
		},
	},
	'遂': {		{
			Tone: 1,
			Words: []string{"不遂", "毛遂"},
		},
	},
	'的': {		{
			Tone: 2,
			Words: []string{"的当", "的确"},
		},
		{
			Tone: 1,
			Words: []string{"目的", "中的"},
		},
	},
	'革': {		{
			Tone: 1,
			Words: []string{"病革"},
		},
	},
	'更': {		{
			Tone: 1,
			Words: []string{"更换", "更事"},
		},
	},
	'喝': {		{
			Tone: 2,
			Words: []string{"喝采", "喝令"},
		},
	},
	'应': {		{
			Tone: 1,
			Words: []string{"应付", "应承"},
		},
	},
	'簸': {		{
			Tone: 1,
			Words: []string{"簸箕"},
		},
	},
	'撮': {		{
			Tone: 4,
			Words: []string{"撮毛"},
		},
	},
	'委': {		{
			Tone: 1,
			Words: []string{"委蛇"},
		},
	},
	'轴': {		{
			Tone: 1,
			Words: []string{"大轴", "压轴"},
		},
	},
	'创': {		{
			Tone: 1,
			Words: []string{"重创", "创伤"},
		},
	},
	'度': {		{
			Tone: 1,
			Words: []string{"忖度", "揣度"},
		},
	},
	'奇': {		{
			Tone: 1,
			Words: []string{"奇偶", "奇数"},
		},
	},
	'埋': {		{
			Tone: 1,
			Words: []string{"埋怨"},
		},
	},
	'卜': {		{
			Tone: 1,
			Words: []string{"占卜"},
		},
	},
	'颈': {		{
			Tone: 1,
			Words: []string{"脖颈"},
		},
	},
	'脉': {		{
			Tone: 1,
			Words: []string{"脉脉"},
		},
	},
	'片': {		{
			Tone: 1,
			Words: []string{"唱片儿"},
		},
	},
	'鲜': {		{
			Tone: 1,
			Words: []string{"鲜见", "鲜为"},
		},
	},
	'单': {		{
			Tone: 1,
			Words: []string{"单于"},
		},
		{
			Tone: 2,
			Words: []string{"单县", "单姓"},
		},
	},
	'巷': {		{
			Tone: 1,
			Words: []string{"巷道"},
		},
	},
	'嚼': {		{
			Tone: 1,
			Words: []string{"嚼舌"},
		},
	},
	'眯': {		{
			Tone: 3,
			Words: []string{"眯眼"},
		},
	},
	'蹊': {		{
			Tone: 1,
			Words: []string{"蹊径"},
		},
	},
	'堡': {		{
			Tone: 3,
			Words: []string{"瓦窑堡", "吴堡"},
		},
		{
			Tone: 1,
			Words: []string{"十里堡"},
		},
	},
	'夹': {		{
			Tone: 2,
			Words: []string{"夹裤", "夹袄"},
		},
	},
	'踉': {		{
			Tone: 2,
			Words: []string{"踉跄"},
		},
	},
	'笼': {		{
			Tone: 1,
			Words: []string{"笼络", "笼统"},
		},
	},
	'背': {		{
			Tone: 1,
			Words: []string{"背包", "背枪"},
		},
	},
	'提': {		{
			Tone: 4,
			Words: []string{"提防", "提溜"},
		},
	},
	'汗': {		{
			Tone: 1,
			Words: []string{"可汗", "大汗"},
		},
	},
	'谷': {		{
			Tone: 2,
			Words: []string{"吐谷"},
		},
	},
	'绿': {		{
			Tone: 1,
			Words: []string{"绿林", "鸭绿"},
		},
	},
	'钻': {		{
			Tone: 1,
			Words: []string{"钻床", "钻杆"},
		},
	},
	'虾': {		{
			Tone: 1,
			Words: []string{"虾蟆"},
		},
	},
	'横': {		{
			Tone: 1,
			Words: []string{"蛮横", "横财"},
		},
	},
	'氓': {		{
			Tone: 1,
			Words: []string{"氓民"},
		},
	},
	'种': {		{
			Tone: 2,
			Words: []string{"耕种", "种植", "播种"},
		},
	},
	'碌': {		{
			Tone: 2,
			Words: []string{"碌碡"},
		},
	},
	'排': {		{
			Tone: 2,
			Words: []string{"排车"},
		},
	},
	'任': {		{
			Tone: 1,
			Words: []string{"任丘", "任姓"},
		},
	},
	'扎': {		{
			Tone: 1,
			Words: []string{"挣扎"},
		},
		{
			Tone: 3,
			Words: []string{"扎彩", "一扎"},
		},
	},
	'龟': {		{
			Tone: 1,
			Words: []string{"龟裂"},
		},
		{
			Tone: 2,
			Words: []string{"龟兹"},
		},
	},
	'卡': {		{
			Tone: 1,
			Words: []string{"关卡", "卡子"},
		},
	},
	'钥': {		{
			Tone: 1,
			Words: []string{"锁钥"},
		},
	},
	'艾': {		{
			Tone: 1,
			Words: []string{"自艾", "惩艾"},
		},
	},
	'扒': {		{
			Tone: 3,
			Words: []string{"扒手", "扒草"},
		},
	},
	'蚌': {		{
			Tone: 3,
			Words: []string{"蚌埠"},
		},
	},
	'泊': {		{
			Tone: 1,
			Words: []string{"淡泊", "停泊"},
		},
	},
	'将': {		{
			Tone: 1,
			Words: []string{"将校", "将兵"},
		},
	},
	'属': {		{
			Tone: 1,
			Words: []string{"属望", "属文", "属意"},
		},
	},
	'折': {		{
			Tone: 1,
			Words: []string{"折本"},
		},
		{
			Tone: 3,
			Words: []string{"折腾"},
		},
		{
			Tone: 1,
			Words: []string{"折合"},
		},
	},
	'苔': {		{
			Tone: 1,
			Words: []string{"青苔", "舌苔"},
		},
	},
	'熏': {		{
			Tone: 1,
			Words: []string{"熏着"},
		},
	},
	'假': {		{
			Tone: 1,
			Words: []string{"假期", "假日"},
		},
	},
	'解': {		{
			Tone: 1,
			Words: []string{"解元", "押解"},
		},
		{
			Tone: 2,
			Words: []string{"解县", "解开", "解不开"},
		},
	},
	'蓝': {		{
			Tone: 1,
			Words: []string{"苤蓝"},
		},
	},
	'弄': {		{
			Tone: 1,
			Words: []string{"弄堂"},
		},
	},
	'掇': {		{
			Tone: 1,
			Words: []string{"撺掇", "掂掇"},
		},
	},
	'空': {		{
			Tone: 2,
			Words: []string{"空白", "空闲"},
		},
	},
	'塞': {		{
			Tone: 1,
			Words: []string{"堵塞", "阻塞"},
		},
		{
			Tone: 2,
			Words: []string{"塞翁", "边塞", "塞外", "塞北"},
		},
	},
	'哑': {		{
			Tone: 1,
			Words: []string{"哑哑"},
		},
	},
	'吭': {		{
			Tone: 1,
			Words: []string{"引吭"},
		},
	},
	'镪': {		{
			Tone: 1,
			Words: []string{"银镪"},
		},
	},
	'趄': {		{
			Tone: 1,
			Words: []string{"趄坡", "趔趄"},
		},
	},
	'散': {		{
			Tone: 1,
			Words: []string{"懒散", "零散", "分散", "散架", "零散"},
		},
	},
	'济': {		{
			Tone: 1,
			Words: []string{"济宁", "济济"},
		},
	},
	'缪': {		{
			Tone: 2,
			Words: []string{"纰缪"},
		},
		{
			Tone: 1,
			Words: []string{"缪氏"},
		},
	},
	'给': {		{
			Tone: 1,
			Words: []string{"补给", "配给"},
		},
	},
	'胖': {		{
			Tone: 2,
			Words: []string{"体胖"},
		},
	},
	'禅': {		{
			Tone: 1,
			Words: []string{"禅让", "封禅"},
		},
	},
	'缉': {		{
			Tone: 1,
			Words: []string{"缉鞋"},
		},
	},
	'喷': {		{
			Tone: 1,
			Words: []string{"喷香"},
		},
	},
	'悄': {		{
			Tone: 1,
			Words: []string{"悄然", "悄寂"},
		},
	},
	'曲': {		{
			Tone: 1,
			Words: []string{"曲调", "曲艺", "曲牌", "小曲"},
		},
	},
	'膊': {		{
			Tone: 3,
			Words: []string{"胳膊"},
		},
		{
			Tone: 3,
			Words: []string{"胳膊"},
		},
	},
	'倒': {		{
			Tone: 1,
			Words: []string{"颠倒", "倒戈", "倒嚼"},
		},
	},
	'囤': {		{
			Tone: 1,
			Words: []string{"囤积"},
		},
	},
	'枸': {		{
			Tone: 2,
			Words: []string{"枸橘"},
		},
	},
	'挨': {		{
			Tone: 1,
			Words: []string{"挨打", "挨说"},
		},
	},
	'豁': {		{
			Tone: 1,
			Words: []string{"豁亮", "豁达"},
		},
	},
	'识': {		{
			Tone: 2,
			Words: []string{"标识", "强识"},
		},
	},
	'省': {		{
			Tone: 1,
			Words: []string{"反省", "省亲"},
		},
	},
	'殖': {		{
			Tone: 2,
			Words: []string{"骨殖"},
		},
	},
	'匙': {		{
			Tone: 1,
			Words: []string{"汤匙"},
		},
	},
	'枞': {		{
			Tone: 1,
			Words: []string{"枞阳"},
		},
	},
	'哈': {		{
			Tone: 4,
			Words: []string{"哈达:姓哈"},
		},
		{
			Tone: 1,
			Words: []string{"哈什玛"},
		},
	},
	'稽': {		{
			Tone: 1,
			Words: []string{"稽首"},
		},
	},
	'混': {		{
			Tone: 2,
			Words: []string{"混浊", "混活"},
		},
	},
	'矩': {		{
			Tone: 1,
			Words: []string{"规矩"},
		},
	},
	'捋': {		{
			Tone: 1,
			Words: []string{"捋袖"},
		},
	},
	'苫': {		{
			Tone: 1,
			Words: []string{"苫屋"},
		},
	},
	'色': {		{
			Tone: 1,
			Words: []string{"落色", "颜色"},
		},
	},
	'屏': {		{
			Tone: 1,
			Words: []string{"屏息:屏气"},
		},
	},
	'分': {		{
			Tone: 1,
			Words: []string{"身分", "分子"},
		},
	},
	'潦': {		{
			Tone: 3,
			Words: []string{"潦草", "潦倒"},
		},
	},
	'迫': {		{
			Tone: 1,
			Words: []string{"迫击"},
		},
	},
	'晕': {		{
			Tone: 1,
			Words: []string{"月晕", "晕车"},
		},
	},
	'攒': {		{
			Tone: 1,
			Words: []string{"攒动", "攒射"},
		},
	},
	'靡': {		{
			Tone: 1,
			Words: []string{"委靡", "披靡"},
		},
	},
	'瓦': {		{
			Tone: 1,
			Words: []string{"瓦刀", "瓦屋"},
		},
	},
	'与': {		{
			Tone: 2,
			Words: []string{"参与"},
		},
	},
	'蠡': {		{
			Tone: 1,
			Words: []string{"蠡县"},
		},
	},
	'络': {		{
			Tone: 1,
			Words: []string{"络子"},
		},
	},
	'厦': {		{
			Tone: 1,
			Words: []string{"厦门", "噶厦"},
		},
	},
	'舍': {		{
			Tone: 1,
			Words: []string{"校舍", "三舍"},
		},
	},
	'蒙': {		{
			Tone: 1,
			Words: []string{"蒙古"},
		},
	},
	'亲': {		{
			Tone: 1,
			Words: []string{"亲家"},
		},
	},
	'镏': {		{
			Tone: 1,
			Words: []string{"金镏"},
		},
	},
	'朴': {		{
			Tone: 3,
			Words: []string{"朴刀"},
		},
		{
			Tone: 1,
			Words: []string{"厚朴", "朴树"},
		},
		{
			Tone: 4,
			Words: []string{"朴姓"},
		},
	},
	'煞': {		{
			Tone: 1,
			Words: []string{"煞白", "恶煞"},
		},
	},
	'冠': {		{
			Tone: 1,
			Words: []string{"冠军", "而冠"},
		},
	},
	'会': {		{
			Tone: 1,
			Words: []string{"会计", "财会"},
		},
	},
	'教': {		{
			Tone: 1,
			Words: []string{"教书", "教给"},
		},
	},
	'淋': {		{
			Tone: 1,
			Words: []string{"淋硝", "淋盐"},
		},
	},
	'扁': {		{
			Tone: 1,
			Words: []string{"扁舟"},
		},
	},
	'阿': {		{
			Tone: 1,
			Words: []string{"阿附", "阿胶"},
		},
	},
	'得': {		{
			Tone: 2,
			Words: []string{"好得"},
		},
		{
			Tone: 1,
			Words: []string{"得喝"},
		},
	},
	'尉': {		{
			Tone: 1,
			Words: []string{"尉迟", "尉犁"},
		},
	},
	'号': {		{
			Tone: 1,
			Words: []string{"呼号", "号叫"},
		},
	},
	'哄': {		{
			Tone: 2,
			Words: []string{"哄骗"},
		},
		{
			Tone: 1,
			Words: []string{"起哄"},
		},
	},
	'薄': {		{
			Tone: 1,
			Words: []string{"单薄", "稀薄"},
		},
	},
	'辟': {		{
			Tone: 1,
			Words: []string{"复辟"},
		},
	},
	'藏': {		{
			Tone: 1,
			Words: []string{"宝藏"},
		},
	},
	'大': {		{
			Tone: 1,
			Words: []string{"大王"},
		},
	},
	'丧': {		{
			Tone: 1,
			Words: []string{"丧乱", "丧钟", "哭丧"},
		},
	},
	'数': {		{
			Tone: 2,
			Words: []string{"数见", "不鲜"},
		},
		{
			Tone: 1,
			Words: []string{"数落", "数数"},
		},
	},
	'调': {		{
			Tone: 1,
			Words: []string{"调皮", "调配", "调和", "配合"},
		},
	},
	'着': {		{
			Tone: 3,
			Words: []string{"着急", "着迷", "着凉"},
		},
		{
			Tone: 1,
			Words: []string{"着落", "着重", "着手"},
		},
		{
			Tone: 2,
			Words: []string{"失着", "着数", "高着"},
		},
	},
	'沓': {		{
			Tone: 1,
			Words: []string{"杂沓", "复沓", "沓来", "疲沓"},
		},
	},
	'长': {		{
			Tone: 1,
			Words: []string{"特长", "取长", "身长", "取长", "长人"},
		},
	},
	'把': {		{
			Tone: 1,
			Words: []string{"印把", "刀把", "话把"},
		},
	},
	'臭': {		{
			Tone: 1,
			Words: []string{"乳臭", "铜臭"},
		},
	},
	'娜': {		{
			Tone: 1,
			Words: []string{"袅娜", "婀娜"},
		},
	},
	'葚': {		{
			Tone: 1,
			Words: []string{"桑葚"},
		},
	},
	'宁': {		{
			Tone: 2,
			Words: []string{"宁可", "宁氏"},
		},
	},
	'似': {		{
			Tone: 1,
			Words: []string{"相似"},
		},
	},
	'熨': {		{
			Tone: 1,
			Words: []string{"熨贴"},
		},
	},
	'差': {		{
			Tone: 1,
			Words: []string{"偏差", "差错"},
		},
	},
	'杆': {		{
			Tone: 2,
			Words: []string{"枪杆", "烟杆"},
		},
	},
	'菌': {		{
			Tone: 1,
			Words: []string{"香菌", "菌子"},
		},
	},
	'俩': {		{
			Tone: 1,
			Words: []string{"伎俩"},
		},
	},
	'校': {		{
			Tone: 1,
			Words: []string{"校场", "校勘"},
		},
	},
	'和': {		{
			Tone: 1,
			Words: []string{"应和", "和诗"},
		},
		{
			Tone: 4,
			Words: []string{"和了", "和牌"},
		},
		{
			Tone: 3,
			Words: []string{"和面", "和泥"},
		},
		{
			Tone: 2,
			Words: []string{"和药", "两和"},
		},
		{
			Tone: 2,
			Words: []string{"搀和", "搅和"},
		},
	},
	'撇': {		{
			Tone: 2,
			Words: []string{"撇嘴", "撇置"},
		},
	},
	'臂': {		{
			Tone: 1,
			Words: []string{"胳臂"},
		},
	},
	'嘲': {		{
			Tone: 1,
			Words: []string{"嘲哳"},
		},
	},
	'供': {		{
			Tone: 1,
			Words: []string{"口供", "上供"},
		},
	},
	'什': {		{
			Tone: 1,
			Words: []string{"什物", "什锦"},
		},
	},
	'正': {		{
			Tone: 1,
			Words: []string{"正月"},
		},
	},
	'茄': {		{
			Tone: 1,
			Words: []string{"茄子"},
		},
	},
	'劲': {		{
			Tone: 1,
			Words: []string{"强劲", "劲草"},
		},
	},
	'难': {		{
			Tone: 1,
			Words: []string{"责难", "难兄", "难弟"},
		},
	},
	'栖': {		{
			Tone: 1,
			Words: []string{"栖栖"},
		},
	},
	'车': {		{
			Tone: 1,
			Words: []string{"车马炮", "吃车"},
		},
	},
	'貉': {		{
			Tone: 2,
			Words: []string{"之貉"},
		},
	},
	'看': {		{
			Tone: 1,
			Words: []string{"看守", "看管"},
		},
	},
	'吁': {		{
			Tone: 1,
			Words: []string{"呼吁", "吁求"},
		},
	},
	'剥': {		{
			Tone: 1,
			Words: []string{"剥皮"},
		},
	},
	'伺': {		{
			Tone: 1,
			Words: []string{"伺机", "环伺"},
		},
	},
	'勒': {		{
			Tone: 1,
			Words: []string{"勒令", "勒索"},
		},
	},
	'轧': {		{
			Tone: 2,
			Words: []string{"轧钢", "轧辊"},
		},
	},
	'奔': {		{
			Tone: 1,
			Words: []string{"投奔"},
		},
	},
	'间': {		{
			Tone: 1,
			Words: []string{"间断", "间谍"},
		},
	},
	'累': {		{
			Tone: 2,
			Words: []string{"累赘"},
		},
		{
			Tone: 1,
			Words: []string{"牵累"},
		},
	},
	'发': {		{
			Tone: 1,
			Words: []string{"理发", "结发"},
		},
	},
	'称': {		{
			Tone: 1,
			Words: []string{"称心", "对称"},
		},
	},
	'偈': {		{
			Tone: 1,
			Words: []string{"偈勇"},
		},
	},
	'馏': {		{
			Tone: 1,
			Words: []string{"馏饭"},
		},
	},
	'幢': {		{
			Tone: 1,
			Words: []string{"一幢"},
		},
	},
	'颤': {		{
			Tone: 1,
			Words: []string{"颤栗", "打颤"},
		},
	},
	'逮': {		{
			Tone: 1,
			Words: []string{"逮捕"},
		},
	},
	'坊': {		{
			Tone: 1,
			Words: []string{"粉坊", "染坊"},
		},
	},
	'咽': {		{
			Tone: 1,
			Words: []string{"咽喉"},
		},
		{
			Tone: 2,
			Words: []string{"呜咽"},
		},
	},
	'缝': {		{
			Tone: 1,
			Words: []string{"缝合"},
		},
	},
	'量': {		{
			Tone: 1,
			Words: []string{"丈量", "计量"},
		},
		{
			Tone: 2,
			Words: []string{"打量", "掂量"},
		},
	},
}
