package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/xuender/oils/base"
)

func main() {
	file := base.Panic1(os.Open("data/dict.txt"))
	reader := bufio.NewReader(file)
	pySet := base.NewSet[string]()
	pyMap := base.NewMap[rune, string]()

	defer file.Close()

	pySet.Add(" ")
	for {
		line, _, err := reader.ReadLine()
		if err == io.EOF {
			break
		}

		str := string(line)
		runes := []rune(str)
		py := string(runes[1:])
		pyMap[runes[0]] = py
		pySet.Add(strings.Split(py, ",")...)
	}

	pySlice := base.NewSlice(pySet.Slice()...)
	sort.Sort(pySlice)
	createTones(pySlice)
	createDict(pyMap, pySlice)
}

func createDict(pyMap base.Map[rune, string], pySlice base.Slice[string]) {
	tones := base.NewMap[rune, []int]()
	max := 0

	for key, value := range pyMap {
		values := strings.Split(value, ",")
		length := len(values)

		if length > max {
			max = length
		}

		tones[key] = make([]int, length)

		for sub, pyStr := range values {
			tones[key][sub] = pySlice.Index(pyStr)
		}
	}

	file := base.Panic1(os.Create("dict_gen.go"))
	defer file.Close()
	_, _ = file.WriteString("// Code generated by dict2data. DO NOT EDIT.\n")
	_, _ = file.WriteString("package gopy\n\n")
	_, _ = file.WriteString("// nolint\n")
	_, _ = file.WriteString(fmt.Sprintf("var dict = map[rune][%d]int16{\n", max))

	for han, pys := range tones {
		s := base.NewSlice(pys...)
		_, _ = file.WriteString(fmt.Sprintf("\t0x%x:{%s},\n", han, s.Join(",")))
	}

	_, _ = file.WriteString("}\n")
}

func createTones(pySlice base.Slice[string]) {
	tonesGo := base.Panic1(os.Create("tones_gen.go"))
	defer tonesGo.Close()

	_, _ = tonesGo.WriteString("// Code generated by dict2data. DO NOT EDIT.\n")
	_, _ = tonesGo.WriteString("package gopy\n\n")
	_, _ = tonesGo.WriteString("var tones = []string{")

	var (
		one   byte = ' '
		index      = 0
	)

	for _, pinyin := range pySlice {
		if index%10 == 0 || one != pinyin[0] {
			if one != pinyin[0] {
				_, _ = tonesGo.WriteString("\n")
			}

			_, _ = tonesGo.WriteString("\n\t")
			index = 0
			one = pinyin[0]
		}

		index++

		_, _ = tonesGo.WriteString("\"")
		_, _ = tonesGo.WriteString(pinyin)
		_, _ = tonesGo.WriteString("\", ")
	}

	_, _ = tonesGo.WriteString("\n}")
}
