package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/xuender/oils/base"
)

func main() {
	file := base.Panic1(os.Open("data/dict.txt"))
	reader := bufio.NewReader(file)
	pySet := base.NewSet[string]()
	pyMap := base.NewMap[rune, string]()

	defer file.Close()

	for {
		line, _, err := reader.ReadLine()
		if err == io.EOF {
			break
		}

		str := string(line)
		runes := []rune(str)
		py := string(runes[1:])
		pyMap[runes[0]] = py
		pySet.Add(strings.Split(py, ",")...)
	}

	pySlice := base.NewSlice(pySet.Slice()...)
	sort.Sort(pySlice)
	createTones(pySlice)
	createData(pyMap, pySlice)
}

func createData(pyMap base.Map[rune, string], pySlice base.Slice[string]) {

	tones := base.NewMap[rune, []int]()

	for key, value := range pyMap {
		values := strings.Split(value, ",")
		tones[key] = make([]int, len(values))

		for sub, pyStr := range values {
			tones[key][sub] = pySlice.Index(pyStr)
		}
	}

	var (
		count int
		file  *os.File
	)

	const num = 2000

	defer file.Close()

	for han, tones := range tones {
		if count%num == 0 {
			if file != nil {
				_, _ = file.WriteString("}\n")
				file.Close()
			}

			file = base.Panic1(os.Create(fmt.Sprintf("data/data%02d_gen.go", count/num)))
			_, _ = file.WriteString("// Code generated by dict2data. DO NOT EDIT.\n")
			_, _ = file.WriteString("package data\n\n")
			_, _ = file.WriteString("// nolint\n")
			_, _ = file.WriteString("func init(){\n")
		}

		count++

		s := base.NewSlice(tones...)
		_, _ = file.WriteString(fmt.Sprintf("\tDict[0x%x]=[]int16{%s}\n", han, s.Join(",")))
	}

	_, _ = file.WriteString("}\n")
}

func createTones(pySlice base.Slice[string]) {
	tonesGo := base.Panic1(os.Create("data/tones_gen.go"))
	defer tonesGo.Close()

	_, _ = tonesGo.WriteString("// Code generated by dict2data. DO NOT EDIT.\n")
	_, _ = tonesGo.WriteString("package data\n\n")
	_, _ = tonesGo.WriteString("var Dict = map[rune][]int16{}\n")
	_, _ = tonesGo.WriteString("var Tones = []string{")

	for index, pinyin := range pySlice {
		if index%10 == 0 {
			_, _ = tonesGo.WriteString("\n\t")
		}

		_, _ = tonesGo.WriteString("\"")
		_, _ = tonesGo.WriteString(pinyin)
		_, _ = tonesGo.WriteString("\", ")
	}

	_, _ = tonesGo.WriteString("\n}")
}
